config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # config/routes.rb
  devise_for :users

  root to: 'recipes#public_recipes'

  get 'public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  
  
  resources :users  do
    resources :recipes, only: %i[index show new create edit update destroy] do
      resources :recipe_food, only: %i[new show create destroy update edit ]
      get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list' do
      end
    end
    resources :inventories, only: %i[index show new create edit update destroy] do
    resources :food_inventories, only: %i[index show new create destroy]
  end
end

  resources :foods, only: %i[index show new create edit update destroy]
  resources :recipes, only: %i[index show new create edit update destroy]

end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :food_inventories
  has_many :food, through: :food_inventories

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @inventories = Inventory.includes(:user).where(user_id: current_user.id).page(params[:page]).per(3)
  end

  def show
    @inventory = Inventory.find(params[:id])
    @inventory_food_inventories = @inventory.food_inventories.includes(:food).page(params[:page]).per(3)
    @food = Food.all
  end

  def new
    @user = User.find(params[:user_id])
    @inventory = @user.inventories.new
  end

  def create
    @user = User.find(params[:user_id])
    @inventory = @user.inventories.new(inventory_params)

    if @inventory.save
      redirect_to user_inventories_path(@user), notice: 'Inventory was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])

    if @inventory.destroy
      redirect_to user_inventories_path(@inventory.user), notice: 'Inventory was destroyed.'
    else
      redirect_to user_inventories_path(@inventory.user), alert: 'Inventory was not deleted.'
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventories/index.html.erb
<%= stylesheet_link_tag 'inventories' %>
<div class="inventories-index-cont">

<div class="inventories-index">
<%= link_to "Add New Inventory", new_user_inventory_path(@user), class: "inventories-index-add" %>


<% if @inventories.any? %>
  <% @inventories.each do |inventory| %>
      <div class="inventories-index-list">

        <div class="inventories-index-actions">

        <h2 class="inventories-index-link"><%= link_to inventory.name, user_inventory_path(inventory.user, inventory) %></h2>
        <% if can?(:destroy, inventory) %>
          <%= button_to "Remove", user_inventory_path(inventory.user, inventory), method: :delete, class: "inventories-index-remove" %>
        <% end %>
        </div>

        <div class="inventories-index-actions"><p class=""><%= inventory.description %></p></div>

      </div>
  <% end %>
<% else %>
  <h2 class="inventories-index-empty"> There's no inventories yet </h2>
<% end %>

<%= paginate @inventories, class:"pagination" %>

<%= render partial: 'shared/back' %>



</div>

</div>

app/views/inventories/new.html.erb
<div class="user-form">
  <div class="user-form-cont">
    <h2 class="user-form-title">New Inventory</h2>
    <%= form_with(class:"forms", model: [current_user, Inventory.new], url: user_inventories_path(current_user), local: true) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="field">
        <%= form.text_field :name, placeholder: "Inventory Name", class: "form-input" %>
      </div>
      <div class="field">
        <%= form.text_field :description, placeholder: "Description", class: "form-input" %>
      </div>
      <%= form.submit "Create Inventory", class: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/inventories/show.html.erb
<%= stylesheet_link_tag 'inventories-show' %>
<div class="inventories-show-cont">
  <div class="inventories-show-main">
    <h1> <%= @inventory.name %> </h1>
    <div class="inventories-show-actions">
      <%= link_to "Add Food", new_user_inventory_food_inventory_path(current_user.id, @inventory.id), class: 'btn'%>
      <%= link_to 'Ingredients List', foods_path, class: 'foods-index-create'  %>
    </div>
    <% if @food.count == 0  %>
      <div>
        <p> No food yet... </p>
      </div>
    <% else %>
      <div class="inventories-show">
        <div class="inventories-show-info">
          <h3 class="inventories-title">Food</h3>
          <h3 class="inventories-title">Quantity</h3>
          <h3 class="inventories-title">Action</h3>
        </div>
        <% @inventory_food_inventories.each do |food_inventory| %>
          <div class="inventories-show-info">
            <p class="inventories-name"> <%= food_inventory.food.name %></p>
            <p class="inventories-quantity"> <%= food_inventory.quantity %> </p>
            <% if can?(:destroy, food_inventory) %>
              <%= button_to "Delete", user_inventory_food_inventory_path(current_user.id, @inventory.id, food_inventory.id), method: :delete, class: "inventories-btn" %>
            <% end %>
          </div>
        <% end  %>
      </div>
      <%= paginate @inventory_food_inventories, class:"pagination" %>
    <% end %>
    <%= render partial: 'shared/back' %>
  </div>
</div>
</div>