config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # config/routes.rb
  devise_for :users

  root to: 'recipes#public_recipes'

  get 'public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  
  
  resources :users  do
    resources :recipes, only: %i[index show new create edit update destroy] do
      resources :recipe_food, only: %i[new show create destroy update edit ]
      get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list' do
      end
    end
    resources :inventories, only: %i[index show new create edit update destroy] do
    resources :food_inventories, only: %i[index show new create destroy]
  end
end

  resources :foods, only: %i[index show new create edit update destroy]
  resources :recipes, only: %i[index show new create edit update destroy]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_food
  has_many :food, foreign_key: 'id'

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true


  def public?
    public
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    @my_recipes = Recipe.where(user_id: current_user.id).page(params[:page]).per(3)
    @recipe_food = RecipeFood.all
    @this_recipe = RecipeFood.where(recipe_id: @recipe)
    @food = Food.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.includes(:food).where(recipe_id: @recipe.id).page(params[:page]).per(3)
    @actual_user = current_user
    @food = Food.all
    @recipe_id = @recipe.id
    @notice = params[:notice] if params[:notice]
    return unless params[:alert]

    @alert = params[:alert]
  end

  def new
    @recipes = Recipe.new
  end

  def create
    @recipes = Recipe.new(recipe_params)
    if @recipes.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      redirect_to new_recipe_path(current_user.id, @recipe.id), alert: 'Recipe was not created.'
    end
  end

  def destroy
    @recipes = Recipe.find(params[:id])
    if @recipes.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully destroyed.'
    else
      redirect_to recipes_path, alert: 'Recipe was not destroyed.'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      puts @recipe.errors.full_messages # Print errors to the console
      render :show, alert: 'Something went wrong'
    end
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).page(params[:page]).per(3)
  end

  def shopping_list(inventory_id = nil)
    @recipe = Recipe.find(params[:recipe_id])
    @recipes = Recipe.where(user_id: current_user.id)
    @recipe_food = RecipeFood.where(recipe_id: @recipes.pluck(:id))
    @ingredient = Food.where(id: @recipe_food.pluck(:food_id))

    @inventory = if inventory_id
                   Inventory.includes([:food]).where(id: inventory_id)
                 else
                   Inventory.where(user_id: current_user.id)
                 end

    @food_inventory = FoodInventory.where(inventory_id: @inventory.pluck(:id))
    @inventory_ingredient = Food.where(id: @food_inventory.pluck(:food_id))

    @food = Food.all
  end



  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<% stylesheet_link_tag 'recipes' %>
<div class="recipes-index-cont">
    <div class="recipes-index">
  <% if @recipes.count == 0 %>
      <%= link_to 'Add New Recipe', new_recipe_path, class: 'recipes-index-add' %>
    <h2 class="recipes-index-empty">There's no recipes yet</h2>
    <style> .recipes-index{ height: 100vh; justify-content: center; align-items: center;} </style>
    <%= render partial: 'shared/back' %>
  <% else %>
      <%= link_to 'Add New Recipe', new_recipe_path, class: 'recipes-index-add' %>
      <% if @my_recipes.any? %>
        <% @my_recipes.map do |recipe| %>
          <div class="recipes-index-list">
            <div class="recipes-index-actions">
              <h2 class="recipes-index-link"><%= link_to recipe.name, user_recipe_path(current_user.id, recipe.id) %></h2>
              <% if can?(:destroy, recipe) %>
                <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: "recipe-index-remove" %>
              <% end %>
            </div>
            <p class="recipes-index-actions"><%= recipe.description %></p>
          </div>
        <% end %>
        <%= paginate @my_recipes, class: 'pagination' %>
      <% else %>
        <h2 class="recipes-index-empty"> There's no recipes yet </h2>
      <% end %>
  <%= render partial: 'shared/back' %>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="user-form">
  <div class="user-form-cont">
    <h2 class="user-form-title">New Recipe</h2>
    <%= form_with(model: [current_user, Recipe.new], class:"forms", url: recipes_path, local: true) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="field">
        <%= form.text_field :name, placeholder: "Recipe Name", class: "form-input" %>
      </div>
      <div class="field">
        <%= form.text_field :description, placeholder: "Description", class: "form-input" %>
      </div>
      <div class="field">
        <%= form.number_field :preparation_time, placeholder: "Preparation time", class: "form-input" %>
      </div>
      <div class="field">
        <%= form.number_field :cooking_time, placeholder: "Cooking time", class: "form-input" %>
      </div>
      <div class="field">
        <%= form.label :public, "Make this recipe public?" %>
        <%= form.check_box :public, class: "form-checkbox" %>
      </div>
      <%= form.submit 'Add recipe', class: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<%# Recipes Public_Recipes %>
<% stylesheet_link_tag "recipes_public" %>
<div class="public-recipes-cont">
  <div class="public-recipes">
    <% @public_recipes.map do |recipe| %>
      <div class="public-recipes-list">
        <div class="public-recipes-actions">
          <h2 class="public-recipes-link"><%= link_to recipe.name, recipe_path(recipe.id) %></h2>
          <p>By: <%= User.find_by(id: recipe.user_id).name %></p>
        </div>
        <div class="public-recipes-actions">
          <p>Total Food Items: <%= RecipeFood.where(recipe_id: recipe.id).count  %></p>
          
            <%@recipe_food_id = RecipeFood.where(recipe_id: recipe.id) %>
            <%@total_recipe_food = @recipe_food_id.map { |food| food.quantity } %>
          
              <% @recipe_food = RecipeFood.where(recipe_id: recipe.id).map do |food| %>
                <% @food_id = food.food_id %>
                <% Food.where(id: @food_id) %>
              <% end %>
              <% @recipe_food.map do |food| %>
                <% food.map {|food| food.price} %>
              <% end %>
              <% @recipe_food %>
              <% @prices = prices_array = @recipe_food.map do |relation| %>
                <% food_item = relation.first %>
                <% food_item.price %>
              <% end %>
              <% result = @total_recipe_food.map.with_index do |total_food, index| %>
                <% @total_price = total_food * @prices[index] %>
              <% end %>
          <p> Total price: $<%= result.sum %></p>
        </div>

      </div>
    <% end %>
    <%= paginate @public_recipes, class: 'pagination' %>
    <%= render partial: 'shared/back' %>
  </div>
</div>

app/views/recipes/shopping_list.html.erb
<%= turbo_frame_tag "shopping_modal" do %>
  <div class="shopping_modal_cont">
    <div class="shopping_modal">
      <% if @inventory.find_by(id: params[:inventory_id]).present? %>
        <h1 class="form-title">Shopping List</h1>
      <% else %>
        <h1 class="form-title">Generating Shopping List</h1>
        <style>
          .form-btn{ align-self: center !important; transform: translateY(6rem);}
        </style>
      <% end %>
      <%= form_with url: user_recipe_shopping_list_path, class: 'forms', method: :get do |form| %>
        <%= form.hidden_field :recipe_id, value: params[:recipe_id] %>
        <div class="field">
          <h3 class="shopping-sub"><%= form.label :inventory_id, 'Choose an inventory to use:' %></h3>
        </div>
        <style> .shopping-sub {text-align: center} </style>
        <div class="form-actions">
          <div class="field">
            <%= form.collection_select(:inventory_id, @inventory, :id, :name, { prompt: true }, { required: true }) %>
          </div class="field">
          <div>
            <%= form.submit 'Generate', class: 'btn', data: { turbo: false } %>
          </div class="field">
        </div>
      <% end %>
      <% if @inventory.present? %>
        <% @selected_inventory = @inventory.find_by(id: params[:inventory_id]) %>
        <!-- Logic -->
        <% if @selected_inventory %>
          <% @inventory_food = @selected_inventory.food_inventories.includes([:food]).map(&:food).compact.sort_by(&:id) %>
          <% @recipe_food = @recipe.recipe_food.includes([:food]).map(&:food).compact.sort_by(&:id) %>
          <% common_length = [@inventory_food.length, @recipe_food.length].min %>
          <% difference = @inventory_food.zip(@recipe_food).count do |a, b| a&.id != nil && b&.id != nil && a.id != b.id end %>
          <!-- Logic -->
          <div class="shopping-char-cont">

          <div class="shopping-char">
            <p>Amount of food to buy: <%= difference %></p>
            <p>
              <%
              total_value = 0 
              food_prices = Food.where(id: @recipe.recipe_food.map { |food| food.food_id }).map { |food| food.price }
              food_quantities = @recipe.recipe_food.map { |food| food.quantity }
              food_prices.each_with_index do |price, index|
              quantity = food_quantities[index]
              product = price * quantity
              total_value += product 
              end
            %>
              <%= "Total value of food needed: #{total_value}" %>
            </p>
          

          </div>  
   
          <div class="shopping-char">
          <p>Inventory: <%= link_to @selected_inventory.name, user_inventory_path(current_user.id, @selected_inventory.id), data: {turbo: false}, class:"form-external-links" %></p>
            <p>Recipe: <%= link_to @recipe.name, user_recipe_path(current_user.id, @recipe.id), data: {turbo: false}, class:"form-external-links" %></p>
          </div>
       </div>

          <style>
            .shopping_modal_cont {background: transparent; backdrop-filter: blur(0px)}
            .shopping_modal { max-width: 40rem; height: 100%; background-color: transparent; border: 0; justify-content: center; align-items: center; }
            .forms { display: none; }
          </style>
          <!-- Logic -->
          <% @recipe_food_id = @recipe.recipe_food.map {|recipe_food| recipe_food.food_id} %>
          <% @recipe_prices = @recipe.recipe_food.map {|recipe_food| recipe_food.food.price} %>
          <% @recipe_quantities = @recipe.recipe_food.map {|recipe_food| recipe_food.quantity} %>
          <% @recipe_total = @recipe_prices.zip(@recipe_quantities).map {|a, b| a * b} %>
          <% @inventory_food_id = @selected_inventory.food_inventories.map {|food_inventory| food_inventory.food_id} %>
          <% @inventory_prices = @selected_inventory.food_inventories.map {|food_inventory| food_inventory.food.price} %>
          <% @inventory_quantities = @selected_inventory.food_inventories.map {|food_inventory| food_inventory.quantity} %>
          <% @inventory_total = @inventory_prices.zip(@inventory_quantities).map {|a, b| a * b} %>
          <!-- Logic -->
          <table>
            <tr>
              <th>Food</th>
              <th>Missing Amount</th>
              <th>Total</th>
            </tr>
            <!-- Logic -->
            <% total_difference = 0 %>
            <% @recipe_food.each_with_index do |recipe_item, index| %>
              <% inventory_item = @selected_inventory.food_inventories.find { |item| item.food_id == recipe_item.id } %>
              <% recipe_price = @recipe_prices[index] * @recipe_quantities[index] %>
              <% if inventory_item.nil? %>
                <% inventory_price = 0 %>
                <% quantity = @recipe_quantities[index] %>
                <% difference = recipe_price %>
              <% else %>
                <% inventory_price = @inventory_prices[index] * inventory_item.quantity %>
                <% quantity = @recipe_quantities[index] - inventory_item.quantity %>
                <% difference = recipe_price - inventory_price %>
              <% end %>
              <% quantity = [quantity, 0].max %>
              <% difference = [difference, 0].max %>
              <% total_difference += difference %>
              <!-- Logic -->
              <tr>
                <td><%= recipe_item.name %></td>
                <td><%= "#{quantity} #{recipe_item.measurement_unit}" %></td>
                <td><%= "$#{difference}" %></td>
              </tr>
            <% end %>
            <tr>
              <td colspan="2"><strong>Total Cost</strong></td>
              <td><strong><%= "$#{total_difference}" %></strong></td>
            </tr>
          </table>
          <style>
            table { border-collapse: collapse; width: 100%; margin-bottom: 20px }
            th, td { border: 1px solid #dddddd; text-align: left; padding: 8px; background-color: #f2f2f2 }
            th { background-color: #f2f2f2 }
            tr:nth-child(even) { background-color: #f2f2f2 }
            td:hover { background-color: #ffffff }
          </style>
          <!-- table with the food name, quantity and price -->
        <% else %>
          <%= link_to 'Cancel',  user_recipes_path(current_user.id), data: {controller: "shopping_modal", action: "close_modal" }, class: "btn form-btn" %>
        <% end %>
      <% else %>
        <p>No inventories available.</p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/show.html.erb
<% stylesheet_link_tag "recipes_show" %>
<% if (@recipe.public || (user_signed_in? && @recipe.user_id == current_user.id)) %>
  <div class="recipes-show-cont">
    <div class="recipes-show-main">
      <h1><%= @recipe.name %></h1>
      <div class="recipes-show-chart">
        <div class="recipes-show-features">
          <p class="recipes-show-prep"> <span>preparation time:</span> <%= @recipe.preparation_time.to_i %> minutes </p>
          <div class="recipes-show-public">
            <% if user_signed_in? %>
              <% if current_user.id == @recipe.user_id %>
                <span>public:</span>
                <%= form_with(model: @recipe, local: true, class:"toggle-button", method: :patch) do |form| %>
                  <%= form.check_box :public, class: "public-toggle", id: "public-toggle", onchange: "this.form.submit();" %>
                  <label class="public-toggle-label" for="public-toggle">
                    <div class="public-toggle-slider"></div>
                  </label>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <p class="recipes-show-cooking"> <span>cooking time:</span> <%= @recipe.cooking_time.to_i %> minutes </p>
        <p class="recipes-show-desc"><%= @recipe.description %> </p>
      </div>
      <% if user_signed_in? %>
        <div class="recipes-show-actions">
          <%= link_to "Generate Shopping List", user_recipe_shopping_list_path(current_user.id, @recipe), remote: true, data: { turbo_frame: "shopping_modal" }, class: "btn" %>
          <% if @recipe.user_id == current_user.id %>
          <%= link_to 'Ingredients List', foods_path, class: 'foods-index-create'  %>
            <%= link_to 'Add Ingredient', new_user_recipe_recipe_food_path(current_user.id, recipe_id: @recipe.id), class: "btn" %>
          <% end %>
        </div>
      <% end %>
      <div class="recipes-show">
        <div class="recipes-show-info">
          <h3 class="recipes-title">Food</h3>
          <h3 class="recipes-title">Quantity</h3>
          <h3 class="recipes-title">Price</h3>
          <% if user_signed_in? %>
            <% if @recipe.user_id == current_user.id  %>
              <style>
                .recipes-show-info{ grid-template-columns: repeat(4, 1fr) }
              </style>
              <h3 class="recipes-title">Actions</h3>
            <% else %>
              <style>
                .recipes-show-info{ grid-template-columns: repeat(3, 1fr) }
              </style>
            <% end %>
          <% else %>
            <style>
              .recipes-show-info{ grid-template-columns: repeat(3, 1fr) }
            </style>
          <% end %>
        </div>
        <% if @recipe_food.present? %>
          <% @recipe_food.map do |recipe_food| %>
            <div class="recipes-show-info">
              <p class="recipes-name"><%= recipe_food.food.name %></p>
              <p class="recipes-quantity"><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></p>
              <p class="recipes-price"><%= (recipe_food.quantity * recipe_food.food.price).to_i %> $ </p>
              <% if user_signed_in? %>
                <% if @recipe.user_id == current_user.id  %>
                  <div class="recipes-upd">
                    <%= link_to 'Modify', edit_user_recipe_recipe_food_path(current_user, @recipe, recipe_food.id), class: "recipes-btn" %>
                    <%= button_to 'Delete', user_recipe_recipe_food_path(current_user.id , @recipe, recipe_food), method: :delete, turbo_confirm: 'Delete recipe?', class: "recipes-btn" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= paginate @recipe_food, class: 'pagination' %>
      <% end %>
      <%= render partial: 'shared/back' %>
    <% else %>
      <h1> You don't have permissons to see this recipe </h1>
      <%= render partial: 'shared/back' %>
    </div>
  </div>
<% end %>