config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # config/routes.rb
  devise_for :users

  root to: 'recipes#public_recipes'

  get 'public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  
  
  resources :users  do
    resources :recipes, only: %i[index show new create edit update destroy] do
      resources :recipe_food, only: %i[new show create destroy update edit ]
      get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list' do
      end
    end
    resources :inventories, only: %i[index show new create edit update destroy] do
    resources :food_inventories, only: %i[index show new create destroy]
  end
end

  resources :foods, only: %i[index show new create edit update destroy]
  resources :recipes, only: %i[index show new create edit update destroy]

end

app/models/food.rb
# app/models/food.rb
class Food < ApplicationRecord
  has_many :food_inventories
  has_many :inventories, through: :food_inventories

  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :price, numericality: { only_integer: true }
  validates :name, presence: true
  validates :measurement_unit, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
      .page(params[:page])
      .page(params[:page]).per(5)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to foods_path
    else
      render 'new'
    end
  end

  def destroy
    @foods = Food.find(params[:id])
    if @foods.destroy
      redirect_to foods_path, notice: 'foods was destroyed'
    else
      redirect_to foods_path, alert: 'foods was not deleted'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'foods' %>
<div class="foods-index-cont">
  <div class="foods-index-options">
    <% if can?(:create, Food)  %>
      <%= link_to 'Add Food', new_food_path, class: 'foods-index-create'  %>
    <% else %>
      <%= link_to 'Create', new_user_registration_path, class: 'foods-index-create'  %>
      <p>or</p>
      <%= link_to 'log in', new_user_session_path, class: 'foods-index-create'  %>
      <p>to an account to add more food!</p>
    <% end  %>
  </div>
  <div class="foods-index">
    <% if Food.count == 0  %>
      <div class="foods-index-info">
        <p class="foods-title"> No food yet... </p>
      </div>
    <% else %>
      <div class="foods-index-info">
        <h3 class="foods-title">Food</h3>
        <h3 class="foods-title">Measurement Unit</h3>
        <h3 class="foods-title">Unit Price</h3>
        <% if can?(:destroy, Food)  %>
          <style>
            .foods-index-info{ grid-template-columns: repeat(4, 1fr) }
          </style>
          <h3 class="foods-title">Actions</h3>
        <% else %>
          <style>
            .foods-index-info{ grid-template-columns: repeat(3, 1fr) }
          </style>
        <% end %>
      </div>
      
      <% @foods.map do |food| %>
        <div class="foods-index-info">
          <p class="foods-name"> <%= food.name %> </p>
          <p class="foods-measurement"> <%= food.measurement_unit %> </p>
          <p class="foods-price"> <%= food.price %>$ </p>
          <% if can?(:destroy, food) %>
            <%= button_to "Delete", food_path(food.id), method: :delete, class: 'foods-delete' %>
          <% end %>
        </div>
      <% end  %>
    <% end %>
      <%= paginate @foods, class: 'pagination' %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="user-form">
  <div class="user-form-cont">
    <h2 class="user-form-title">New Food</h2>
    <%= form_with(class:"forms", model: [current_user, Food.new], url: foods_path, local: true) do |form| %>
      <div class="field">
        <%= form.text_field :name, placeholder: "Food Name", class: "form-input" %>
      </div>
      <div class="field">
        <%= form.select :measurement_unit, options_for_select(['Miligrams', 'Grams', 'Kilograms', 'Liters']), {}, { class: "form-input", placeholder: "Select a Measurement Unit" } %>
      </div>
      <div class="field">
        <%= form.number_field :price, placeholder: "Price", class: "form-input" %>
      </div>
      <%= form.submit 'Add Food', class: "submit-btn" %>
    <% end %>
  </div>
</div>