config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # config/routes.rb
  devise_for :users

  root to: 'recipes#public_recipes'

  get 'public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  
  
  resources :users  do
    resources :recipes, only: %i[index show new create edit update destroy] do
      resources :recipe_food, only: %i[new show create destroy update edit ]
      get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list' do
      end
    end
    resources :inventories, only: %i[index show new create edit update destroy] do
    resources :food_inventories, only: %i[index show new create destroy]
  end
end

  resources :foods, only: %i[index show new create edit update destroy]
  resources :recipes, only: %i[index show new create edit update destroy]

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food, foreign_key: 'food_id'

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/recipe_food_controller.rb
class RecipeFoodController < ApplicationController
  def index
    @recipe_food = RecipeFood.all
  end

  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food.recipe = @recipe
    @ability = Ability.new(current_user)
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_id = params[:recipe_id]
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe_id), notice: 'The ingredient was successfully updated.'
    else
      redirect_to recipe_path(@recipe_id), alert: 'The ingredient could not be updated.'
    end
  end

  def create
    @recipe_id = params[:recipe_id]
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(@recipe_id), notice: 'Recipe Food was successfully created.'
    else
      redirect_to recipe_path(@recipe_id), alert: 'Recipe Food was not created.'
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_id = params[:recipe_id]
    if @recipe_food.destroy
      redirect_to recipe_path(@recipe_id), notice: 'The ingredient was successfully created.'
    else
      redirect_to recipe_path(@recipe_id), alert: 'Recipe Food was not destroyed.'
    end
  end

  private

  # the parametters are: quantity, recipe_id, food_id
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/views/recipe_food/edit.html.erb
<div class="user-form">
  <div class="user-form-cont">
    <h2 class="user-form-title">Edit Ingredient</h2>
    <%= form_with(class:"forms", model: @recipe_food, url: user_recipe_recipe_food_path(current_user, @recipe.id, @recipe_food), local: true, method: :patch) do |form| %>
      <div class="field">
        <div>
          <%= form.label :quantity %>
          <%= form.text_field :quantity, rows: 4, placeholder: "Quantity", class: "form-input", required: true %>
        </div>
        <div>
          <%= form.label :food_id %>
          <%= form.collection_select(:food_id, Food.all, :id, :name, { include_blank: "Select ingredient" }, { class: "form-input", required: true }) %>
        </div>
      </div>
      <%= form.submit 'Update Ingredient', class: "submit-btn" %>
      <%= link_to "Go back", :back, class: 'shared-link go-back' %>
    <% end %>
  </div>
</div>

app/views/recipe_food/new.html.erb
<% if user_signed_in? %>
  <div class="user-form">
    <div class="user-form-cont">
      <h2 class="user-form-title">New Ingredient</h2>

      <%= form_with(model: [current_user, RecipeFood.new], url: user_recipe_recipe_food_index_path(current_user.id), local: true) do |form| %>
      <style>  body > div.user-form > div > form{ width: 100%} </style>
        <div class="field">
          <div>
            <%= form.text_field :quantity, rows: 4, placeholder: "Quantity", class: "form-input", required: true %>
          </div>
          <div>
            <%= form.hidden_field :recipe_id, value: @recipe.id %>

            <%= form.collection_select(:food_id, Food.all, :id, :name, { include_blank: "Select Food" }, { class: "form-input", required: true }) %>
          </div>
        </div>
        <%= form.submit 'Add Ingredient', class: "submit-btn" %>

        <div class="shared-links">
        <%= link_to "Go back", :back, class: 'shared-link go-back' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>